import { getAllVehicles } from './vehicleService';
import type { Vehicle } from '../types/vehicle';

export interface LeaseDeal {
  id: string;
  vehicle: Vehicle;
  monthlyPayment: string;
  monthlyPaymentNum: number;
  term: string;
  dueAtSigning: string;
  mileageAllowance: string;
  expirationDate: string;
  programName: string;
  programDescription: string;
  trimsEligible: string[];
}

const CURRENT_MONTH = new Date().toLocaleString('default', { month: 'long' });
const CURRENT_YEAR = new Date().getFullYear();
const EXPIRATION_DATE = `April 1, ${CURRENT_YEAR}`;

const LEASE_DEAL_DEFS: (Omit<LeaseDeal, 'id' | 'vehicle'> & { make: string; model: string })[] = [
  {
    make: 'Chevrolet',
    model: 'Trax',
    monthlyPayment: '$299',
    monthlyPaymentNum: 299,
    term: '24 months',
    dueAtSigning: '$1,879',
    mileageAllowance: '10,000 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Chevrolet Trax Ultra-Low Mileage Lease',
    programDescription: 'Ultra low-mileage lease for 24 months with $1,879 due at signing. No security deposit required.',
    trimsEligible: ['LS', '1RS'],
  },
  {
    make: 'Chevrolet',
    model: 'Equinox',
    monthlyPayment: '$329',
    monthlyPaymentNum: 329,
    term: '36 months',
    dueAtSigning: '$2,499',
    mileageAllowance: '10,000 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Chevrolet Equinox Lease Special',
    programDescription: 'Lease a new Equinox for 36 months with competitive due at signing. Available through GM Financial.',
    trimsEligible: ['LS', 'LT'],
  },
  {
    make: 'Toyota',
    model: 'Camry',
    monthlyPayment: '$329',
    monthlyPaymentNum: 329,
    term: '36 months',
    dueAtSigning: '$2,999',
    mileageAllowance: '10,000 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Toyota Camry Lease Offer',
    programDescription: 'Lease a new Camry LE for 36 months through Toyota Financial Services. $2,999 due at signing.',
    trimsEligible: ['LE', 'SE'],
  },
  {
    make: 'Toyota',
    model: 'RAV4',
    monthlyPayment: '$359',
    monthlyPaymentNum: 359,
    term: '36 months',
    dueAtSigning: '$2,799',
    mileageAllowance: '10,000 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Toyota RAV4 Lease Special',
    programDescription: 'Lease a new RAV4 LE for 36 months. $2,799 due at signing through Toyota Financial Services.',
    trimsEligible: ['LE', 'XLE'],
  },
  {
    make: 'Honda',
    model: 'CR-V',
    monthlyPayment: '$369',
    monthlyPaymentNum: 369,
    term: '36 months',
    dueAtSigning: '$3,499',
    mileageAllowance: '10,000 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Honda CR-V Lease Offer',
    programDescription: 'Lease a 2025 CR-V LX for 36 months. $3,499 due at signing through Honda Financial Services.',
    trimsEligible: ['LX', 'EX'],
  },
  {
    make: 'Honda',
    model: 'Civic',
    monthlyPayment: '$289',
    monthlyPaymentNum: 289,
    term: '36 months',
    dueAtSigning: '$2,499',
    mileageAllowance: '10,000 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Honda Civic Lease Special',
    programDescription: 'Lease a 2025 Civic LX for 36 months. $2,499 due at signing through Honda Financial Services.',
    trimsEligible: ['LX', 'Sport'],
  },
  {
    make: 'Hyundai',
    model: 'Tucson',
    monthlyPayment: '$339',
    monthlyPaymentNum: 339,
    term: '36 months',
    dueAtSigning: '$2,999',
    mileageAllowance: '10,000 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Hyundai Tucson Lease Event',
    programDescription: 'Lease a new Tucson SE for 36 months. $2,999 due at signing through Hyundai Motor Finance.',
    trimsEligible: ['SE', 'SEL'],
  },
  {
    make: 'Nissan',
    model: 'Rogue',
    monthlyPayment: '$349',
    monthlyPaymentNum: 349,
    term: '36 months',
    dueAtSigning: '$2,799',
    mileageAllowance: '10,000 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Nissan Rogue Lease Offer',
    programDescription: 'Lease a new Rogue S for 36 months. $2,799 due at signing through NMAC.',
    trimsEligible: ['S', 'SV'],
  },
  {
    make: 'Kia',
    model: 'Seltos',
    monthlyPayment: '$279',
    monthlyPaymentNum: 279,
    term: '36 months',
    dueAtSigning: '$2,299',
    mileageAllowance: '10,000 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Kia Seltos Lease Special',
    programDescription: 'Lease a new Seltos LX for 36 months. $2,299 due at signing through Kia Finance America.',
    trimsEligible: ['LX', 'S'],
  },
  {
    make: 'Toyota',
    model: 'Corolla',
    monthlyPayment: '$249',
    monthlyPaymentNum: 249,
    term: '36 months',
    dueAtSigning: '$2,199',
    mileageAllowance: '12,000 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Toyota Corolla Lease Offer',
    programDescription: 'Lease a new Corolla LE for 36 months. $2,199 due at signing through Toyota Financial Services.',
    trimsEligible: ['LE', 'SE'],
  },
  {
    make: 'Honda',
    model: 'Accord',
    monthlyPayment: '$379',
    monthlyPaymentNum: 379,
    term: '36 months',
    dueAtSigning: '$3,299',
    mileageAllowance: '12,000 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Honda Accord Lease Special',
    programDescription: 'Lease a 2025 Accord LX for 36 months. $3,299 due at signing through Honda Financial Services.',
    trimsEligible: ['LX', 'EX'],
  },
  {
    make: 'Mazda',
    model: 'CX-5',
    monthlyPayment: '$339',
    monthlyPaymentNum: 339,
    term: '36 months',
    dueAtSigning: '$2,899',
    mileageAllowance: '10,000 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Mazda CX-5 Lease Event',
    programDescription: 'Lease a 2026 CX-5 S for 36 months. $2,899 due at signing through Mazda Financial Services.',
    trimsEligible: ['S', 'S Select'],
  },
  {
    make: 'Hyundai',
    model: 'Sonata',
    monthlyPayment: '$309',
    monthlyPaymentNum: 309,
    term: '36 months',
    dueAtSigning: '$2,699',
    mileageAllowance: '10,000 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Hyundai Sonata Lease Offer',
    programDescription: 'Lease a new Sonata SE for 36 months. $2,699 due at signing through Hyundai Motor Finance.',
    trimsEligible: ['SE', 'SEL'],
  },
  {
    make: 'Kia',
    model: 'K5',
    monthlyPayment: '$299',
    monthlyPaymentNum: 299,
    term: '36 months',
    dueAtSigning: '$2,499',
    mileageAllowance: '10,000 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Kia K5 Lease Special',
    programDescription: 'Lease a new K5 LXS for 36 months. $2,499 due at signing through Kia Finance America.',
    trimsEligible: ['LXS', 'GT-Line'],
  },
  {
    make: 'Nissan',
    model: 'Altima',
    monthlyPayment: '$319',
    monthlyPaymentNum: 319,
    term: '36 months',
    dueAtSigning: '$2,599',
    mileageAllowance: '12,000 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Nissan Altima Lease Offer',
    programDescription: 'Lease a new Altima S for 36 months. $2,599 due at signing through NMAC.',
    trimsEligible: ['S', 'SV'],
  },
  {
    make: 'Volkswagen',
    model: 'Jetta',
    monthlyPayment: '$259',
    monthlyPaymentNum: 259,
    term: '36 months',
    dueAtSigning: '$2,099',
    mileageAllowance: '10,000 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Volkswagen Jetta Lease Event',
    programDescription: 'Lease a 2025 Jetta S for 36 months. $2,099 due at signing through VW Credit.',
    trimsEligible: ['S', 'SE'],
  },
  {
    make: 'Subaru',
    model: 'Crosstrek',
    monthlyPayment: '$329',
    monthlyPaymentNum: 329,
    term: '36 months',
    dueAtSigning: '$2,799',
    mileageAllowance: '10,000 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Subaru Crosstrek Lease Offer',
    programDescription: 'Lease a 2025 Crosstrek Base for 36 months. $2,799 due at signing through Subaru Motors Finance.',
    trimsEligible: ['Base', 'Premium'],
  },
  {
    make: 'Subaru',
    model: 'Forester',
    monthlyPayment: '$359',
    monthlyPaymentNum: 359,
    term: '36 months',
    dueAtSigning: '$2,999',
    mileageAllowance: '10,000 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Subaru Forester Lease Special',
    programDescription: 'Lease a 2025 Forester Base for 36 months. $2,999 due at signing through Subaru Motors Finance.',
    trimsEligible: ['Base', 'Premium'],
  },
  {
    make: 'Honda',
    model: 'HR-V',
    monthlyPayment: '$269',
    monthlyPaymentNum: 269,
    term: '36 months',
    dueAtSigning: '$2,399',
    mileageAllowance: '12,000 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Honda HR-V Lease Offer',
    programDescription: 'Lease a 2025 HR-V LX for 36 months. $2,399 due at signing through Honda Financial Services.',
    trimsEligible: ['LX', 'Sport'],
  },
  {
    make: 'Hyundai',
    model: 'Kona',
    monthlyPayment: '$259',
    monthlyPaymentNum: 259,
    term: '36 months',
    dueAtSigning: '$2,199',
    mileageAllowance: '10,000 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Hyundai Kona Lease Event',
    programDescription: 'Lease a new Kona SE for 36 months. $2,199 due at signing through Hyundai Motor Finance.',
    trimsEligible: ['SE', 'SEL'],
  },
  {
    make: 'Chevrolet',
    model: 'Trailblazer',
    monthlyPayment: '$289',
    monthlyPaymentNum: 289,
    term: '24 months',
    dueAtSigning: '$1,999',
    mileageAllowance: '10,000 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Chevrolet Trailblazer Lease Special',
    programDescription: 'Ultra low-mileage lease for 24 months with $1,999 due at signing. No security deposit required.',
    trimsEligible: ['LS', 'LT'],
  },
  {
    make: 'Nissan',
    model: 'Kicks',
    monthlyPayment: '$229',
    monthlyPaymentNum: 229,
    term: '36 months',
    dueAtSigning: '$1,999',
    mileageAllowance: '12,000 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Nissan Kicks Lease Offer',
    programDescription: 'Lease a new Kicks S for 36 months. $1,999 due at signing through NMAC.',
    trimsEligible: ['S', 'SV'],
  },
  {
    make: 'Kia',
    model: 'Sportage Hybrid',
    monthlyPayment: '$349',
    monthlyPaymentNum: 349,
    term: '36 months',
    dueAtSigning: '$2,999',
    mileageAllowance: '10,000 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Kia Sportage Hybrid Lease Event',
    programDescription: 'Lease a 2026 Sportage Hybrid LX for 36 months. $2,999 due at signing through Kia Finance America.',
    trimsEligible: ['LX', 'EX'],
  },
  {
    make: 'Toyota',
    model: 'Highlander',
    monthlyPayment: '$419',
    monthlyPaymentNum: 419,
    term: '36 months',
    dueAtSigning: '$3,799',
    mileageAllowance: '10,000 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Toyota Highlander Lease Special',
    programDescription: 'Lease a 2025 Highlander LE for 36 months. $3,799 due at signing through Toyota Financial Services.',
    trimsEligible: ['LE', 'XLE'],
  },
  {
    make: 'Hyundai',
    model: 'Santa Fe',
    monthlyPayment: '$389',
    monthlyPaymentNum: 389,
    term: '36 months',
    dueAtSigning: '$3,199',
    mileageAllowance: '10,000 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Hyundai Santa Fe Lease Offer',
    programDescription: 'Lease a 2026 Santa Fe SE for 36 months. $3,199 due at signing through Hyundai Motor Finance.',
    trimsEligible: ['SE', 'SEL'],
  },
  {
    make: 'Ford',
    model: 'Maverick',
    monthlyPayment: '$309',
    monthlyPaymentNum: 309,
    term: '36 months',
    dueAtSigning: '$2,699',
    mileageAllowance: '10,500 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Ford Maverick Lease Offer',
    programDescription: 'Lease a 2025 Maverick XL for 36 months. $2,699 due at signing through Ford Motor Credit.',
    trimsEligible: ['XL', 'XLT'],
  },
  {
    make: 'Ford',
    model: 'F-150',
    monthlyPayment: '$449',
    monthlyPaymentNum: 449,
    term: '36 months',
    dueAtSigning: '$3,999',
    mileageAllowance: '10,500 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Ford F-150 Lease Event',
    programDescription: 'Lease a 2025 F-150 XL for 36 months. $3,999 due at signing through Ford Motor Credit.',
    trimsEligible: ['XL', 'XLT'],
  },
  {
    make: 'Chevrolet',
    model: 'Silverado',
    monthlyPayment: '$459',
    monthlyPaymentNum: 459,
    term: '36 months',
    dueAtSigning: '$4,199',
    mileageAllowance: '10,000 mi/yr',
    expirationDate: EXPIRATION_DATE,
    programName: 'Chevrolet Silverado Lease Special',
    programDescription: 'Lease a 2024 Silverado 1500 WT for 36 months. $4,199 due at signing. No security deposit required.',
    trimsEligible: ['WT', 'Custom'],
  },
];

export const getLeaseDeals = (): LeaseDeal[] => {
  const allVehicles = getAllVehicles();
  const deals: LeaseDeal[] = [];
  for (const def of LEASE_DEAL_DEFS) {
    const vehicle = allVehicles.find(
      (v) =>
        v.make.toLowerCase() === def.make.toLowerCase() &&
        v.model.toLowerCase() === def.model.toLowerCase() &&
        parseInt(v.year) >= 2024
    );
    if (vehicle) {
      deals.push({
        id: `lease-deal-${vehicle.id}`,
        vehicle,
        monthlyPayment: def.monthlyPayment,
        monthlyPaymentNum: def.monthlyPaymentNum,
        term: def.term,
        dueAtSigning: def.dueAtSigning,
        mileageAllowance: def.mileageAllowance,
        expirationDate: def.expirationDate,
        programName: def.programName,
        programDescription: def.programDescription,
        trimsEligible: def.trimsEligible,
      });
    }
  }
  return deals.sort((a, b) => a.monthlyPaymentNum - b.monthlyPaymentNum);
};

export const getCurrentPeriod = (): { month: string; year: number } => ({
  month: CURRENT_MONTH,
  year: CURRENT_YEAR,
});
