// Trim Service - Provides accurate trim data with detailed specifications for all vehicles

export interface TrimSpecs {
  engine: string;
  horsepower: string;
  torque: string;
  transmission: string;
  drivetrain: string;
  fuelEconomy: string;
  seating: string;
  cargo: string;
  // Feature availability
  heatedSeats: boolean;
  ventilatedSeats: boolean;
  leatherSeats: boolean;
  sunroof: boolean;
  navigationSystem: boolean;
  premiumAudio: boolean;
  wirelessCharging: boolean;
  remoteStart: boolean;
  adaptiveCruise: boolean;
  blindSpotMonitor: boolean;
  laneDepartureWarning: boolean;
  automaticEmergencyBraking: boolean;
  parkingAssist: boolean;
  surroundViewCamera: boolean;
  headsUpDisplay: boolean;
}

export interface TrimData {
  id: string;
  name: string;
  price: string;
  features: string[];
  recommended?: boolean;
  specs?: TrimSpecs;
}

interface VehicleTrims {
  [key: string]: TrimData[];
}

// Helper to create base specs with defaults
const createSpecs = (overrides: Partial<TrimSpecs>): TrimSpecs => ({
  engine: '—',
  horsepower: '—',
  torque: '—',
  transmission: '—',
  drivetrain: 'FWD',
  fuelEconomy: '—',
  seating: '5',
  cargo: '—',
  heatedSeats: false,
  ventilatedSeats: false,
  leatherSeats: false,
  sunroof: false,
  navigationSystem: false,
  premiumAudio: false,
  wirelessCharging: false,
  remoteStart: false,
  adaptiveCruise: false,
  blindSpotMonitor: false,
  laneDepartureWarning: true, // Most modern cars have this standard
  automaticEmergencyBraking: true, // Most modern cars have this standard
  parkingAssist: false,
  surroundViewCamera: false,
  headsUpDisplay: false,
  ...overrides,
});

// Comprehensive trim data for all vehicles with detailed specifications
const vehicleTrims: VehicleTrims = {
  // ============== TOYOTA ==============
  'Toyota Corolla': [
    { 
      id: 'l', 
      name: 'L', 
      price: '$22,050', 
      features: ['7.0" touchscreen', 'Apple CarPlay/Android Auto', 'Toyota Safety Sense', 'LED headlights', 'Auto climate'],
      specs: createSpecs({
        engine: '2.0L 4-Cylinder',
        horsepower: '169 hp',
        torque: '151 lb-ft',
        transmission: 'CVT',
        drivetrain: 'FWD',
        fuelEconomy: '31/40 mpg',
        cargo: '13.1 cu ft',
      }),
    },
    { 
      id: 'le', 
      name: 'LE', 
      price: '$23,150', 
      features: ['All L features', '8.0" touchscreen', 'Blind spot monitor', 'Rear cross traffic alert', 'Upgraded audio'],
      specs: createSpecs({
        engine: '2.0L 4-Cylinder',
        horsepower: '169 hp',
        torque: '151 lb-ft',
        transmission: 'CVT',
        drivetrain: 'FWD',
        fuelEconomy: '31/40 mpg',
        cargo: '13.1 cu ft',
        blindSpotMonitor: true,
      }),
    },
    { 
      id: 'se', 
      name: 'SE', 
      price: '$25,550', 
      features: ['All LE features', 'Sport suspension', '18" wheels', 'Sport seats', 'Paddle shifters'],
      recommended: true,
      specs: createSpecs({
        engine: '2.0L 4-Cylinder',
        horsepower: '169 hp',
        torque: '151 lb-ft',
        transmission: 'CVT',
        drivetrain: 'FWD',
        fuelEconomy: '31/38 mpg',
        cargo: '13.1 cu ft',
        blindSpotMonitor: true,
      }),
    },
    { 
      id: 'xle', 
      name: 'XLE', 
      price: '$27,050', 
      features: ['All LE features', 'SofTex seats', 'Heated seats', '9.0" touchscreen', 'JBL audio'],
      specs: createSpecs({
        engine: '2.0L 4-Cylinder',
        horsepower: '169 hp',
        torque: '151 lb-ft',
        transmission: 'CVT',
        drivetrain: 'FWD',
        fuelEconomy: '31/40 mpg',
        cargo: '13.1 cu ft',
        heatedSeats: true,
        leatherSeats: true,
        premiumAudio: true,
        blindSpotMonitor: true,
        wirelessCharging: true,
      }),
    },
    { 
      id: 'xse', 
      name: 'XSE', 
      price: '$28,600', 
      features: ['All SE + XLE features', 'Dual exhaust', 'Sport styling', 'Premium audio', 'Moonroof'],
      specs: createSpecs({
        engine: '2.0L 4-Cylinder',
        horsepower: '169 hp',
        torque: '151 lb-ft',
        transmission: 'CVT',
        drivetrain: 'FWD',
        fuelEconomy: '31/38 mpg',
        cargo: '13.1 cu ft',
        heatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        premiumAudio: true,
        blindSpotMonitor: true,
        wirelessCharging: true,
      }),
    },
  ],

  'Toyota Camry': [
    { 
      id: 'le', 
      name: 'LE', 
      price: '$28,400', 
      features: ['8.0" touchscreen', 'Apple CarPlay/Android Auto', 'Toyota Safety Sense 3.0', 'LED headlights', 'Dual-zone climate'],
      specs: createSpecs({
        engine: '2.5L 4-Cylinder',
        horsepower: '203 hp',
        torque: '184 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'FWD',
        fuelEconomy: '28/39 mpg',
        cargo: '15.1 cu ft',
      }),
    },
    { 
      id: 'se', 
      name: 'SE', 
      price: '$29,900', 
      features: ['All LE features', 'Sport suspension', '19" wheels', 'Sport seats', 'Paddle shifters'],
      recommended: true,
      specs: createSpecs({
        engine: '2.5L 4-Cylinder',
        horsepower: '203 hp',
        torque: '184 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'FWD',
        fuelEconomy: '28/39 mpg',
        cargo: '15.1 cu ft',
        blindSpotMonitor: true,
      }),
    },
    { 
      id: 'xle', 
      name: 'XLE', 
      price: '$32,120', 
      features: ['All LE features', 'Leather seats', 'Heated seats', 'Moonroof', 'JBL audio'],
      specs: createSpecs({
        engine: '2.5L 4-Cylinder',
        horsepower: '203 hp',
        torque: '184 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'FWD',
        fuelEconomy: '28/39 mpg',
        cargo: '15.1 cu ft',
        heatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        premiumAudio: true,
        blindSpotMonitor: true,
        wirelessCharging: true,
        remoteStart: true,
      }),
    },
    { 
      id: 'xse', 
      name: 'XSE', 
      price: '$33,620', 
      features: ['All SE + XLE features', 'Panoramic roof', 'Ventilated seats', 'Navigation', 'Heads-up display'],
      specs: createSpecs({
        engine: '2.5L 4-Cylinder',
        horsepower: '203 hp',
        torque: '184 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'FWD',
        fuelEconomy: '28/39 mpg',
        cargo: '15.1 cu ft',
        heatedSeats: true,
        ventilatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        navigationSystem: true,
        premiumAudio: true,
        blindSpotMonitor: true,
        wirelessCharging: true,
        remoteStart: true,
        headsUpDisplay: true,
        adaptiveCruise: true,
      }),
    },
    { 
      id: 'xse-v6', 
      name: 'XSE V6', 
      price: '$36,920', 
      features: ['All XSE features', '3.5L V6 engine', '301 horsepower', 'Premium leather', 'Adaptive cruise'],
      specs: createSpecs({
        engine: '3.5L V6',
        horsepower: '301 hp',
        torque: '267 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'FWD',
        fuelEconomy: '22/33 mpg',
        cargo: '15.1 cu ft',
        heatedSeats: true,
        ventilatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        navigationSystem: true,
        premiumAudio: true,
        blindSpotMonitor: true,
        wirelessCharging: true,
        remoteStart: true,
        headsUpDisplay: true,
        adaptiveCruise: true,
        parkingAssist: true,
      }),
    },
  ],

  'Toyota RAV4': [
    { 
      id: 'le', 
      name: 'LE', 
      price: '$31,380', 
      features: ['8.0" touchscreen', 'Apple CarPlay/Android Auto', 'Toyota Safety Sense 2.5+', 'LED headlights', 'AWD'],
      specs: createSpecs({
        engine: '2.5L 4-Cylinder',
        horsepower: '203 hp',
        torque: '184 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'AWD',
        fuelEconomy: '27/35 mpg',
        cargo: '37.5 cu ft',
      }),
    },
    { 
      id: 'xle', 
      name: 'XLE', 
      price: '$34,080', 
      features: ['All LE features', 'Blind spot monitor', 'Power liftgate', 'Roof rails', 'Heated seats'],
      recommended: true,
      specs: createSpecs({
        engine: '2.5L 4-Cylinder',
        horsepower: '203 hp',
        torque: '184 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'AWD',
        fuelEconomy: '27/35 mpg',
        cargo: '37.5 cu ft',
        heatedSeats: true,
        blindSpotMonitor: true,
        remoteStart: true,
      }),
    },
    { 
      id: 'xle-premium', 
      name: 'XLE Premium', 
      price: '$37,280', 
      features: ['All XLE features', 'Moonroof', 'SofTex seats', 'Wireless charging', 'Digital rearview mirror'],
      specs: createSpecs({
        engine: '2.5L 4-Cylinder',
        horsepower: '203 hp',
        torque: '184 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'AWD',
        fuelEconomy: '27/35 mpg',
        cargo: '37.5 cu ft',
        heatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        blindSpotMonitor: true,
        wirelessCharging: true,
        remoteStart: true,
      }),
    },
    { 
      id: 'adventure', 
      name: 'Adventure', 
      price: '$39,280', 
      features: ['All XLE features', 'Dynamic Torque Vectoring AWD', 'Multi-terrain select', 'Unique styling', 'Tow package'],
      specs: createSpecs({
        engine: '2.5L 4-Cylinder',
        horsepower: '203 hp',
        torque: '184 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'AWD',
        fuelEconomy: '26/33 mpg',
        cargo: '37.5 cu ft',
        heatedSeats: true,
        leatherSeats: true,
        blindSpotMonitor: true,
        wirelessCharging: true,
        remoteStart: true,
      }),
    },
    { 
      id: 'limited', 
      name: 'Limited', 
      price: '$41,580', 
      features: ['All XLE Premium features', 'Leather seats', 'Ventilated seats', 'JBL audio', 'Panoramic view monitor'],
      specs: createSpecs({
        engine: '2.5L 4-Cylinder',
        horsepower: '203 hp',
        torque: '184 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'AWD',
        fuelEconomy: '27/35 mpg',
        cargo: '37.5 cu ft',
        heatedSeats: true,
        ventilatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        premiumAudio: true,
        blindSpotMonitor: true,
        wirelessCharging: true,
        remoteStart: true,
        surroundViewCamera: true,
        adaptiveCruise: true,
        parkingAssist: true,
      }),
    },
  ],

  'Toyota Highlander': [
    { 
      id: 'l', 
      name: 'L', 
      price: '$39,420', 
      features: ['8.0" touchscreen', 'Apple CarPlay/Android Auto', 'Toyota Safety Sense 2.5+', 'LED headlights', '8 passenger'],
      specs: createSpecs({
        engine: '2.4L Turbo 4-Cylinder',
        horsepower: '265 hp',
        torque: '309 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'FWD',
        fuelEconomy: '24/30 mpg',
        seating: '8',
        cargo: '16.0 cu ft',
      }),
    },
    { 
      id: 'le', 
      name: 'LE', 
      price: '$42,020', 
      features: ['All L features', 'Power liftgate', 'Roof rails', 'Blind spot monitor', 'Tri-zone climate'],
      specs: createSpecs({
        engine: '2.4L Turbo 4-Cylinder',
        horsepower: '265 hp',
        torque: '309 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'FWD',
        fuelEconomy: '24/30 mpg',
        seating: '8',
        cargo: '16.0 cu ft',
        blindSpotMonitor: true,
      }),
    },
    { 
      id: 'xle', 
      name: 'XLE', 
      price: '$46,225', 
      features: ['All LE features', 'SofTex seats', 'Heated seats', 'Moonroof', 'Navigation'],
      recommended: true,
      specs: createSpecs({
        engine: '2.4L Turbo 4-Cylinder',
        horsepower: '265 hp',
        torque: '309 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'AWD',
        fuelEconomy: '22/29 mpg',
        seating: '8',
        cargo: '16.0 cu ft',
        heatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        navigationSystem: true,
        blindSpotMonitor: true,
        wirelessCharging: true,
        remoteStart: true,
      }),
    },
    { 
      id: 'limited', 
      name: 'Limited', 
      price: '$50,725', 
      features: ['All XLE features', 'Leather seats', 'Ventilated seats', 'JBL audio', 'Digital rearview mirror'],
      specs: createSpecs({
        engine: '2.4L Turbo 4-Cylinder',
        horsepower: '265 hp',
        torque: '309 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'AWD',
        fuelEconomy: '22/29 mpg',
        seating: '7',
        cargo: '16.0 cu ft',
        heatedSeats: true,
        ventilatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        navigationSystem: true,
        premiumAudio: true,
        blindSpotMonitor: true,
        wirelessCharging: true,
        remoteStart: true,
        adaptiveCruise: true,
        surroundViewCamera: true,
      }),
    },
    { 
      id: 'platinum', 
      name: 'Platinum', 
      price: '$53,325', 
      features: ['All Limited features', 'Panoramic roof', 'Head-up display', '12.3" touchscreen', 'Premium interior'],
      specs: createSpecs({
        engine: '2.4L Turbo 4-Cylinder',
        horsepower: '265 hp',
        torque: '309 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'AWD',
        fuelEconomy: '22/29 mpg',
        seating: '7',
        cargo: '16.0 cu ft',
        heatedSeats: true,
        ventilatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        navigationSystem: true,
        premiumAudio: true,
        blindSpotMonitor: true,
        wirelessCharging: true,
        remoteStart: true,
        adaptiveCruise: true,
        surroundViewCamera: true,
        headsUpDisplay: true,
        parkingAssist: true,
      }),
    },
  ],

  // ============== HONDA ==============
  'Honda Civic': [
    { 
      id: 'lx', 
      name: 'LX', 
      price: '$24,950', 
      features: ['7.0" touchscreen', 'Apple CarPlay/Android Auto', 'Honda Sensing', 'Auto climate', 'LED headlights'],
      specs: createSpecs({
        engine: '2.0L 4-Cylinder',
        horsepower: '158 hp',
        torque: '138 lb-ft',
        transmission: 'CVT',
        drivetrain: 'FWD',
        fuelEconomy: '31/40 mpg',
        cargo: '14.8 cu ft',
      }),
    },
    { 
      id: 'sport', 
      name: 'Sport', 
      price: '$27,050', 
      features: ['All LX features', '18" wheels', 'Sport pedals', 'Rear spoiler', 'Chrome exhaust'],
      specs: createSpecs({
        engine: '2.0L 4-Cylinder',
        horsepower: '158 hp',
        torque: '138 lb-ft',
        transmission: 'CVT',
        drivetrain: 'FWD',
        fuelEconomy: '30/37 mpg',
        cargo: '14.8 cu ft',
      }),
    },
    { 
      id: 'ex', 
      name: 'EX', 
      price: '$28,650', 
      features: ['All Sport features', '9.0" touchscreen', 'Wireless charging', 'Moonroof', 'Remote start'],
      recommended: true,
      specs: createSpecs({
        engine: '1.5L Turbo 4-Cylinder',
        horsepower: '180 hp',
        torque: '177 lb-ft',
        transmission: 'CVT',
        drivetrain: 'FWD',
        fuelEconomy: '33/42 mpg',
        cargo: '14.8 cu ft',
        sunroof: true,
        wirelessCharging: true,
        remoteStart: true,
        blindSpotMonitor: true,
      }),
    },
    { 
      id: 'touring', 
      name: 'Touring', 
      price: '$31,450', 
      features: ['All EX features', 'Leather seats', 'Heated seats', 'Bose audio', 'Navigation'],
      specs: createSpecs({
        engine: '1.5L Turbo 4-Cylinder',
        horsepower: '180 hp',
        torque: '177 lb-ft',
        transmission: 'CVT',
        drivetrain: 'FWD',
        fuelEconomy: '33/42 mpg',
        cargo: '14.8 cu ft',
        heatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        navigationSystem: true,
        premiumAudio: true,
        wirelessCharging: true,
        remoteStart: true,
        blindSpotMonitor: true,
        adaptiveCruise: true,
      }),
    },
  ],

  'Honda Accord': [
    { 
      id: 'lx', 
      name: 'LX', 
      price: '$28,990', 
      features: ['8.0" touchscreen', 'Apple CarPlay/Android Auto', 'Honda Sensing', 'Auto climate', 'LED headlights'],
      specs: createSpecs({
        engine: '1.5L Turbo 4-Cylinder',
        horsepower: '192 hp',
        torque: '192 lb-ft',
        transmission: 'CVT',
        drivetrain: 'FWD',
        fuelEconomy: '29/37 mpg',
        cargo: '16.7 cu ft',
      }),
    },
    { 
      id: 'ex', 
      name: 'EX', 
      price: '$31,610', 
      features: ['All LX features', '12.3" touchscreen', 'Wireless charging', 'Moonroof', 'Remote start'],
      specs: createSpecs({
        engine: '1.5L Turbo 4-Cylinder',
        horsepower: '192 hp',
        torque: '192 lb-ft',
        transmission: 'CVT',
        drivetrain: 'FWD',
        fuelEconomy: '29/37 mpg',
        cargo: '16.7 cu ft',
        sunroof: true,
        wirelessCharging: true,
        remoteStart: true,
        blindSpotMonitor: true,
      }),
    },
    { 
      id: 'sport', 
      name: 'Sport', 
      price: '$32,990', 
      features: ['All EX features', '19" wheels', 'Sport styling', 'Rear spoiler', 'Dual exhaust'],
      recommended: true,
      specs: createSpecs({
        engine: '1.5L Turbo 4-Cylinder',
        horsepower: '192 hp',
        torque: '192 lb-ft',
        transmission: 'CVT',
        drivetrain: 'FWD',
        fuelEconomy: '29/37 mpg',
        cargo: '16.7 cu ft',
        sunroof: true,
        wirelessCharging: true,
        remoteStart: true,
        blindSpotMonitor: true,
      }),
    },
    { 
      id: 'ex-l', 
      name: 'EX-L', 
      price: '$34,510', 
      features: ['All EX features', 'Leather seats', 'Heated seats', 'Memory seats', 'Bose audio'],
      specs: createSpecs({
        engine: '1.5L Turbo 4-Cylinder',
        horsepower: '192 hp',
        torque: '192 lb-ft',
        transmission: 'CVT',
        drivetrain: 'FWD',
        fuelEconomy: '29/37 mpg',
        cargo: '16.7 cu ft',
        heatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        premiumAudio: true,
        wirelessCharging: true,
        remoteStart: true,
        blindSpotMonitor: true,
      }),
    },
    { 
      id: 'touring', 
      name: 'Touring', 
      price: '$38,990', 
      features: ['All EX-L features', 'Ventilated seats', 'Head-up display', 'Parking sensors', 'Premium audio'],
      specs: createSpecs({
        engine: '2.0L Turbo 4-Cylinder',
        horsepower: '252 hp',
        torque: '273 lb-ft',
        transmission: '10-Speed Auto',
        drivetrain: 'FWD',
        fuelEconomy: '24/34 mpg',
        cargo: '16.7 cu ft',
        heatedSeats: true,
        ventilatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        navigationSystem: true,
        premiumAudio: true,
        wirelessCharging: true,
        remoteStart: true,
        blindSpotMonitor: true,
        adaptiveCruise: true,
        headsUpDisplay: true,
        parkingAssist: true,
        surroundViewCamera: true,
      }),
    },
  ],

  'Honda CR-V': [
    { 
      id: 'lx', 
      name: 'LX', 
      price: '$30,050', 
      features: ['7.0" touchscreen', 'Apple CarPlay/Android Auto', 'Honda Sensing', 'Auto climate', 'LED headlights'],
      specs: createSpecs({
        engine: '1.5L Turbo 4-Cylinder',
        horsepower: '190 hp',
        torque: '179 lb-ft',
        transmission: 'CVT',
        drivetrain: 'FWD',
        fuelEconomy: '28/34 mpg',
        cargo: '36.3 cu ft',
      }),
    },
    { 
      id: 'ex', 
      name: 'EX', 
      price: '$33,150', 
      features: ['All LX features', '9.0" touchscreen', 'Wireless charging', 'Moonroof', 'Remote start'],
      recommended: true,
      specs: createSpecs({
        engine: '1.5L Turbo 4-Cylinder',
        horsepower: '190 hp',
        torque: '179 lb-ft',
        transmission: 'CVT',
        drivetrain: 'AWD',
        fuelEconomy: '27/32 mpg',
        cargo: '36.3 cu ft',
        sunroof: true,
        wirelessCharging: true,
        remoteStart: true,
        blindSpotMonitor: true,
      }),
    },
    { 
      id: 'ex-l', 
      name: 'EX-L', 
      price: '$36,250', 
      features: ['All EX features', 'Leather seats', 'Heated seats', 'Power liftgate', 'Memory seats'],
      specs: createSpecs({
        engine: '1.5L Turbo 4-Cylinder',
        horsepower: '190 hp',
        torque: '179 lb-ft',
        transmission: 'CVT',
        drivetrain: 'AWD',
        fuelEconomy: '27/32 mpg',
        cargo: '36.3 cu ft',
        heatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        wirelessCharging: true,
        remoteStart: true,
        blindSpotMonitor: true,
      }),
    },
    { 
      id: 'touring', 
      name: 'Touring', 
      price: '$39,550', 
      features: ['All EX-L features', 'Ventilated seats', 'Wireless CarPlay', 'Bose audio', 'Navigation'],
      specs: createSpecs({
        engine: '1.5L Turbo 4-Cylinder',
        horsepower: '190 hp',
        torque: '179 lb-ft',
        transmission: 'CVT',
        drivetrain: 'AWD',
        fuelEconomy: '27/32 mpg',
        cargo: '36.3 cu ft',
        heatedSeats: true,
        ventilatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        navigationSystem: true,
        premiumAudio: true,
        wirelessCharging: true,
        remoteStart: true,
        blindSpotMonitor: true,
        adaptiveCruise: true,
        parkingAssist: true,
      }),
    },
  ],

  'Honda Pilot': [
    { 
      id: 'lx', 
      name: 'LX', 
      price: '$40,250', 
      features: ['8.0" touchscreen', 'Apple CarPlay/Android Auto', 'Honda Sensing', 'Tri-zone climate', 'LED headlights'],
      specs: createSpecs({
        engine: '3.5L V6',
        horsepower: '285 hp',
        torque: '262 lb-ft',
        transmission: '10-Speed Auto',
        drivetrain: 'FWD',
        fuelEconomy: '20/27 mpg',
        seating: '8',
        cargo: '18.6 cu ft',
      }),
    },
    { 
      id: 'ex', 
      name: 'EX', 
      price: '$43,650', 
      features: ['All LX features', 'Power liftgate', 'Moonroof', 'Heated seats', 'Remote start'],
      specs: createSpecs({
        engine: '3.5L V6',
        horsepower: '285 hp',
        torque: '262 lb-ft',
        transmission: '10-Speed Auto',
        drivetrain: 'AWD',
        fuelEconomy: '19/26 mpg',
        seating: '8',
        cargo: '18.6 cu ft',
        heatedSeats: true,
        sunroof: true,
        remoteStart: true,
        blindSpotMonitor: true,
      }),
    },
    { 
      id: 'ex-l', 
      name: 'EX-L', 
      price: '$46,600', 
      features: ['All EX features', 'Leather seats', 'Memory seats', 'Bose audio', 'Wireless charging'],
      recommended: true,
      specs: createSpecs({
        engine: '3.5L V6',
        horsepower: '285 hp',
        torque: '262 lb-ft',
        transmission: '10-Speed Auto',
        drivetrain: 'AWD',
        fuelEconomy: '19/26 mpg',
        seating: '8',
        cargo: '18.6 cu ft',
        heatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        premiumAudio: true,
        wirelessCharging: true,
        remoteStart: true,
        blindSpotMonitor: true,
      }),
    },
    { 
      id: 'touring', 
      name: 'Touring', 
      price: '$50,550', 
      features: ['All EX-L features', 'Ventilated seats', 'Rear entertainment', 'Navigation', 'Parking sensors'],
      specs: createSpecs({
        engine: '3.5L V6',
        horsepower: '285 hp',
        torque: '262 lb-ft',
        transmission: '10-Speed Auto',
        drivetrain: 'AWD',
        fuelEconomy: '19/26 mpg',
        seating: '7',
        cargo: '18.6 cu ft',
        heatedSeats: true,
        ventilatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        navigationSystem: true,
        premiumAudio: true,
        wirelessCharging: true,
        remoteStart: true,
        blindSpotMonitor: true,
        adaptiveCruise: true,
        parkingAssist: true,
        surroundViewCamera: true,
      }),
    },
    { 
      id: 'elite', 
      name: 'Elite', 
      price: '$53,650', 
      features: ['All Touring features', 'Panoramic roof', 'Heads-up display', 'Wireless charging', 'CabinWatch'],
      specs: createSpecs({
        engine: '3.5L V6',
        horsepower: '285 hp',
        torque: '262 lb-ft',
        transmission: '10-Speed Auto',
        drivetrain: 'AWD',
        fuelEconomy: '19/26 mpg',
        seating: '7',
        cargo: '18.6 cu ft',
        heatedSeats: true,
        ventilatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        navigationSystem: true,
        premiumAudio: true,
        wirelessCharging: true,
        remoteStart: true,
        blindSpotMonitor: true,
        adaptiveCruise: true,
        parkingAssist: true,
        surroundViewCamera: true,
        headsUpDisplay: true,
      }),
    },
  ],

  // ============== FORD ==============
  'Ford F-150': [
    { 
      id: 'xl', 
      name: 'XL', 
      price: '$36,495', 
      features: ['8.0" touchscreen', 'Apple CarPlay/Android Auto', 'Ford Co-Pilot360', 'Pro Trailer Backup', 'LED headlights'],
      specs: createSpecs({
        engine: '3.3L V6',
        horsepower: '290 hp',
        torque: '265 lb-ft',
        transmission: '10-Speed Auto',
        drivetrain: 'RWD',
        fuelEconomy: '20/24 mpg',
        seating: '3',
        cargo: '52.8 cu ft (bed)',
      }),
    },
    { 
      id: 'xlt', 
      name: 'XLT', 
      price: '$44,970', 
      features: ['All XL features', '12.0" touchscreen', 'SYNC 4', 'Power tailgate', 'Remote start'],
      recommended: true,
      specs: createSpecs({
        engine: '2.7L EcoBoost V6',
        horsepower: '325 hp',
        torque: '400 lb-ft',
        transmission: '10-Speed Auto',
        drivetrain: '4WD',
        fuelEconomy: '20/26 mpg',
        seating: '6',
        cargo: '52.8 cu ft (bed)',
        remoteStart: true,
        blindSpotMonitor: true,
      }),
    },
    { 
      id: 'lariat', 
      name: 'Lariat', 
      price: '$54,070', 
      features: ['All XLT features', 'Leather seats', 'Heated/ventilated seats', 'B&O audio', 'Power running boards'],
      specs: createSpecs({
        engine: '3.5L EcoBoost V6',
        horsepower: '400 hp',
        torque: '500 lb-ft',
        transmission: '10-Speed Auto',
        drivetrain: '4WD',
        fuelEconomy: '18/24 mpg',
        seating: '6',
        cargo: '52.8 cu ft (bed)',
        heatedSeats: true,
        ventilatedSeats: true,
        leatherSeats: true,
        premiumAudio: true,
        wirelessCharging: true,
        remoteStart: true,
        blindSpotMonitor: true,
        adaptiveCruise: true,
      }),
    },
    { 
      id: 'king-ranch', 
      name: 'King Ranch', 
      price: '$65,745', 
      features: ['All Lariat features', 'King Ranch styling', 'Multicontour seats', 'Trailer Tow package', 'Premium leather'],
      specs: createSpecs({
        engine: '3.5L EcoBoost V6',
        horsepower: '400 hp',
        torque: '500 lb-ft',
        transmission: '10-Speed Auto',
        drivetrain: '4WD',
        fuelEconomy: '18/24 mpg',
        seating: '6',
        cargo: '52.8 cu ft (bed)',
        heatedSeats: true,
        ventilatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        navigationSystem: true,
        premiumAudio: true,
        wirelessCharging: true,
        remoteStart: true,
        blindSpotMonitor: true,
        adaptiveCruise: true,
        parkingAssist: true,
        surroundViewCamera: true,
      }),
    },
    { 
      id: 'platinum', 
      name: 'Platinum', 
      price: '$67,915', 
      features: ['All Lariat features', 'Platinum styling', 'Massage seats', 'Tech Package', 'Power deploy running boards'],
      specs: createSpecs({
        engine: '3.5L EcoBoost V6',
        horsepower: '400 hp',
        torque: '500 lb-ft',
        transmission: '10-Speed Auto',
        drivetrain: '4WD',
        fuelEconomy: '18/24 mpg',
        seating: '6',
        cargo: '52.8 cu ft (bed)',
        heatedSeats: true,
        ventilatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        navigationSystem: true,
        premiumAudio: true,
        wirelessCharging: true,
        remoteStart: true,
        blindSpotMonitor: true,
        adaptiveCruise: true,
        parkingAssist: true,
        surroundViewCamera: true,
        headsUpDisplay: true,
      }),
    },
  ],

  'Ford Mustang': [
    { 
      id: 'ecoboost', 
      name: 'EcoBoost', 
      price: '$32,515', 
      features: ['2.3L EcoBoost', '315hp', '12.4" digital cluster', 'SYNC 4', 'Track Apps'],
      specs: createSpecs({
        engine: '2.3L EcoBoost 4-Cylinder',
        horsepower: '315 hp',
        torque: '350 lb-ft',
        transmission: '6-Speed Manual',
        drivetrain: 'RWD',
        fuelEconomy: '22/33 mpg',
        seating: '4',
        cargo: '13.5 cu ft',
      }),
    },
    { 
      id: 'ecoboost-premium', 
      name: 'EcoBoost Premium', 
      price: '$39,015', 
      features: ['All EcoBoost features', 'Leather seats', 'B&O audio', 'Digital dash', 'Active exhaust'],
      recommended: true,
      specs: createSpecs({
        engine: '2.3L EcoBoost 4-Cylinder',
        horsepower: '315 hp',
        torque: '350 lb-ft',
        transmission: '10-Speed Auto',
        drivetrain: 'RWD',
        fuelEconomy: '22/33 mpg',
        seating: '4',
        cargo: '13.5 cu ft',
        heatedSeats: true,
        leatherSeats: true,
        premiumAudio: true,
        blindSpotMonitor: true,
      }),
    },
    { 
      id: 'gt', 
      name: 'GT', 
      price: '$43,315', 
      features: ['5.0L V8 486hp', 'Performance brakes', 'Launch control', 'Line-lock', 'Track Apps'],
      specs: createSpecs({
        engine: '5.0L V8',
        horsepower: '486 hp',
        torque: '418 lb-ft',
        transmission: '6-Speed Manual',
        drivetrain: 'RWD',
        fuelEconomy: '16/26 mpg',
        seating: '4',
        cargo: '13.5 cu ft',
      }),
    },
    { 
      id: 'gt-premium', 
      name: 'GT Premium', 
      price: '$49,815', 
      features: ['All GT features', 'Leather seats', 'B&O audio', 'MagneRide damping', 'Recaro seats available'],
      specs: createSpecs({
        engine: '5.0L V8',
        horsepower: '486 hp',
        torque: '418 lb-ft',
        transmission: '10-Speed Auto',
        drivetrain: 'RWD',
        fuelEconomy: '16/26 mpg',
        seating: '4',
        cargo: '13.5 cu ft',
        heatedSeats: true,
        ventilatedSeats: true,
        leatherSeats: true,
        premiumAudio: true,
        blindSpotMonitor: true,
        adaptiveCruise: true,
      }),
    },
    { 
      id: 'dark-horse', 
      name: 'Dark Horse', 
      price: '$60,775', 
      features: ['5.0L V8 500hp', 'Track-focused suspension', 'Torsen diff', 'Brembo brakes', 'Unique styling'],
      specs: createSpecs({
        engine: '5.0L V8',
        horsepower: '500 hp',
        torque: '418 lb-ft',
        transmission: '6-Speed Manual',
        drivetrain: 'RWD',
        fuelEconomy: '15/24 mpg',
        seating: '4',
        cargo: '13.5 cu ft',
        heatedSeats: true,
        ventilatedSeats: true,
        leatherSeats: true,
        premiumAudio: true,
        blindSpotMonitor: true,
      }),
    },
  ],

  // ============== CHEVROLET ==============
  'Chevrolet Silverado': [
    { 
      id: 'wt', 
      name: 'WT', 
      price: '$37,645', 
      features: ['2.7L Turbo', '7.0" touchscreen', 'Apple CarPlay', 'Trailering package', 'Auto Emergency Braking'],
      specs: createSpecs({
        engine: '2.7L Turbo 4-Cylinder',
        horsepower: '310 hp',
        torque: '430 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'RWD',
        fuelEconomy: '20/23 mpg',
        seating: '3',
        cargo: '71.7 cu ft (bed)',
      }),
    },
    { 
      id: 'custom', 
      name: 'Custom', 
      price: '$42,595', 
      features: ['All WT features', '20" wheels', 'LED headlights', 'Remote start', 'Body-color bumpers'],
      specs: createSpecs({
        engine: '2.7L Turbo 4-Cylinder',
        horsepower: '310 hp',
        torque: '430 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: '4WD',
        fuelEconomy: '18/21 mpg',
        seating: '6',
        cargo: '71.7 cu ft (bed)',
        remoteStart: true,
      }),
    },
    { 
      id: 'lt', 
      name: 'LT', 
      price: '$47,695', 
      features: ['All Custom features', '5.3L V8', '13.4" touchscreen', 'Heated seats', 'Power driver seat'],
      recommended: true,
      specs: createSpecs({
        engine: '5.3L V8',
        horsepower: '355 hp',
        torque: '383 lb-ft',
        transmission: '10-Speed Auto',
        drivetrain: '4WD',
        fuelEconomy: '16/22 mpg',
        seating: '6',
        cargo: '71.7 cu ft (bed)',
        heatedSeats: true,
        remoteStart: true,
        blindSpotMonitor: true,
      }),
    },
    { 
      id: 'ltz', 
      name: 'LTZ', 
      price: '$55,995', 
      features: ['All LT features', 'Leather seats', 'Ventilated seats', 'Surround Vision', 'Adaptive cruise'],
      specs: createSpecs({
        engine: '5.3L V8',
        horsepower: '355 hp',
        torque: '383 lb-ft',
        transmission: '10-Speed Auto',
        drivetrain: '4WD',
        fuelEconomy: '16/22 mpg',
        seating: '6',
        cargo: '71.7 cu ft (bed)',
        heatedSeats: true,
        ventilatedSeats: true,
        leatherSeats: true,
        premiumAudio: true,
        wirelessCharging: true,
        remoteStart: true,
        blindSpotMonitor: true,
        adaptiveCruise: true,
        surroundViewCamera: true,
      }),
    },
    { 
      id: 'high-country', 
      name: 'High Country', 
      price: '$62,795', 
      features: ['All LTZ features', '6.2L V8', 'Super Cruise avail', 'Premium leather', 'Exclusive styling'],
      specs: createSpecs({
        engine: '6.2L V8',
        horsepower: '420 hp',
        torque: '460 lb-ft',
        transmission: '10-Speed Auto',
        drivetrain: '4WD',
        fuelEconomy: '15/20 mpg',
        seating: '6',
        cargo: '71.7 cu ft (bed)',
        heatedSeats: true,
        ventilatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        navigationSystem: true,
        premiumAudio: true,
        wirelessCharging: true,
        remoteStart: true,
        blindSpotMonitor: true,
        adaptiveCruise: true,
        surroundViewCamera: true,
        headsUpDisplay: true,
        parkingAssist: true,
      }),
    },
  ],

  // ============== HYUNDAI ==============
  'Hyundai Tucson': [
    { 
      id: 'se', 
      name: 'SE', 
      price: '$29,250', 
      features: ['8.0" touchscreen', 'Apple CarPlay/Android Auto', 'SmartSense safety', 'LED headlights', 'Rear camera'],
      specs: createSpecs({
        engine: '2.5L 4-Cylinder',
        horsepower: '187 hp',
        torque: '178 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'FWD',
        fuelEconomy: '26/33 mpg',
        cargo: '38.7 cu ft',
      }),
    },
    { 
      id: 'sel', 
      name: 'SEL', 
      price: '$31,550', 
      features: ['All SE features', 'Blind spot monitor', '10.25" touchscreen', 'Wireless charging', 'Power liftgate'],
      recommended: true,
      specs: createSpecs({
        engine: '2.5L 4-Cylinder',
        horsepower: '187 hp',
        torque: '178 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'AWD',
        fuelEconomy: '25/31 mpg',
        cargo: '38.7 cu ft',
        blindSpotMonitor: true,
        wirelessCharging: true,
      }),
    },
    { 
      id: 'xrt', 
      name: 'XRT', 
      price: '$34,050', 
      features: ['All SEL features', 'XRT styling', 'All-terrain tires', 'Roof rails', 'Increased ride height'],
      specs: createSpecs({
        engine: '2.5L 4-Cylinder',
        horsepower: '187 hp',
        torque: '178 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'AWD',
        fuelEconomy: '24/29 mpg',
        cargo: '38.7 cu ft',
        blindSpotMonitor: true,
        wirelessCharging: true,
        remoteStart: true,
      }),
    },
    { 
      id: 'limited', 
      name: 'Limited', 
      price: '$38,550', 
      features: ['All SEL features', 'Leather seats', 'Ventilated seats', 'Bose audio', 'Panoramic sunroof'],
      specs: createSpecs({
        engine: '2.5L 4-Cylinder',
        horsepower: '187 hp',
        torque: '178 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'AWD',
        fuelEconomy: '25/31 mpg',
        cargo: '38.7 cu ft',
        heatedSeats: true,
        ventilatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        premiumAudio: true,
        blindSpotMonitor: true,
        wirelessCharging: true,
        remoteStart: true,
        adaptiveCruise: true,
        surroundViewCamera: true,
      }),
    },
  ],

  'Hyundai Sonata': [
    { 
      id: 'se', 
      name: 'SE', 
      price: '$28,550', 
      features: ['8.0" touchscreen', 'Apple CarPlay/Android Auto', 'Smart Safety Suite', 'LED headlights', 'Auto climate'],
      specs: createSpecs({
        engine: '2.5L 4-Cylinder',
        horsepower: '191 hp',
        torque: '181 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'FWD',
        fuelEconomy: '28/38 mpg',
        cargo: '16.0 cu ft',
      }),
    },
    { 
      id: 'sel', 
      name: 'SEL', 
      price: '$30,150', 
      features: ['All SE features', '10.25" touchscreen', 'Heated seats', 'Remote start', 'Wireless charging'],
      recommended: true,
      specs: createSpecs({
        engine: '2.5L 4-Cylinder',
        horsepower: '191 hp',
        torque: '181 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'FWD',
        fuelEconomy: '28/38 mpg',
        cargo: '16.0 cu ft',
        heatedSeats: true,
        wirelessCharging: true,
        remoteStart: true,
        blindSpotMonitor: true,
      }),
    },
    { 
      id: 'sel-plus', 
      name: 'SEL Plus', 
      price: '$32,650', 
      features: ['All SEL features', 'Panoramic sunroof', 'Bose audio', 'Ventilated seats', 'Digital key'],
      specs: createSpecs({
        engine: '2.5L 4-Cylinder',
        horsepower: '191 hp',
        torque: '181 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'FWD',
        fuelEconomy: '28/38 mpg',
        cargo: '16.0 cu ft',
        heatedSeats: true,
        ventilatedSeats: true,
        sunroof: true,
        premiumAudio: true,
        wirelessCharging: true,
        remoteStart: true,
        blindSpotMonitor: true,
      }),
    },
    { 
      id: 'limited', 
      name: 'Limited', 
      price: '$35,900', 
      features: ['All SEL Plus features', 'Leather seats', 'HDA II', 'Parking assist', 'Premium audio'],
      specs: createSpecs({
        engine: '2.5L 4-Cylinder',
        horsepower: '191 hp',
        torque: '181 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'FWD',
        fuelEconomy: '28/38 mpg',
        cargo: '16.0 cu ft',
        heatedSeats: true,
        ventilatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        navigationSystem: true,
        premiumAudio: true,
        wirelessCharging: true,
        remoteStart: true,
        blindSpotMonitor: true,
        adaptiveCruise: true,
        parkingAssist: true,
        surroundViewCamera: true,
      }),
    },
    { 
      id: 'n-line', 
      name: 'N Line', 
      price: '$35,400', 
      features: ['All SEL features', '290hp Turbo', 'Sport suspension', 'N Line styling', 'Dual exhaust'],
      specs: createSpecs({
        engine: '2.5L Turbo 4-Cylinder',
        horsepower: '290 hp',
        torque: '311 lb-ft',
        transmission: '8-Speed DCT',
        drivetrain: 'FWD',
        fuelEconomy: '27/34 mpg',
        cargo: '16.0 cu ft',
        heatedSeats: true,
        ventilatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        premiumAudio: true,
        wirelessCharging: true,
        remoteStart: true,
        blindSpotMonitor: true,
      }),
    },
  ],

  // ============== TESLA ==============
  'Tesla Model 3': [
    { 
      id: 'rwd', 
      name: 'Rear-Wheel Drive', 
      price: '$40,240', 
      features: ['15.4" touchscreen', 'Autopilot', '272-mile range', 'Glass roof', 'Premium audio'],
      specs: createSpecs({
        engine: 'Single Motor Electric',
        horsepower: '271 hp',
        torque: '317 lb-ft',
        transmission: 'Single-Speed',
        drivetrain: 'RWD',
        fuelEconomy: '132 MPGe',
        cargo: '23 cu ft',
        heatedSeats: true,
        navigationSystem: true,
        premiumAudio: true,
        adaptiveCruise: true,
        blindSpotMonitor: true,
        automaticEmergencyBraking: true,
      }),
    },
    { 
      id: 'long-range-awd', 
      name: 'Long Range AWD', 
      price: '$47,240', 
      features: ['All RWD features', 'Dual Motor AWD', '333-mile range', 'Premium connectivity', 'Fast charging'],
      recommended: true,
      specs: createSpecs({
        engine: 'Dual Motor Electric',
        horsepower: '366 hp',
        torque: '376 lb-ft',
        transmission: 'Single-Speed',
        drivetrain: 'AWD',
        fuelEconomy: '131 MPGe',
        cargo: '23 cu ft',
        heatedSeats: true,
        navigationSystem: true,
        premiumAudio: true,
        adaptiveCruise: true,
        blindSpotMonitor: true,
        automaticEmergencyBraking: true,
        surroundViewCamera: true,
      }),
    },
    { 
      id: 'performance', 
      name: 'Performance', 
      price: '$53,240', 
      features: ['All Long Range features', '3.1s 0-60', 'Track Mode', 'Carbon spoiler', 'Performance brakes'],
      specs: createSpecs({
        engine: 'Dual Motor Electric',
        horsepower: '510 hp',
        torque: '471 lb-ft',
        transmission: 'Single-Speed',
        drivetrain: 'AWD',
        fuelEconomy: '117 MPGe',
        cargo: '23 cu ft',
        heatedSeats: true,
        navigationSystem: true,
        premiumAudio: true,
        adaptiveCruise: true,
        blindSpotMonitor: true,
        automaticEmergencyBraking: true,
        surroundViewCamera: true,
      }),
    },
  ],

  'Tesla Model Y': [
    { 
      id: 'rwd', 
      name: 'Rear-Wheel Drive', 
      price: '$44,990', 
      features: ['15.4" touchscreen', 'Autopilot', '260-mile range', 'Glass roof', '5 seats'],
      specs: createSpecs({
        engine: 'Single Motor Electric',
        horsepower: '283 hp',
        torque: '317 lb-ft',
        transmission: 'Single-Speed',
        drivetrain: 'RWD',
        fuelEconomy: '129 MPGe',
        cargo: '68 cu ft',
        heatedSeats: true,
        navigationSystem: true,
        premiumAudio: true,
        adaptiveCruise: true,
        blindSpotMonitor: true,
        automaticEmergencyBraking: true,
      }),
    },
    { 
      id: 'long-range-awd', 
      name: 'Long Range AWD', 
      price: '$49,990', 
      features: ['All RWD features', 'Dual Motor AWD', '310-mile range', 'Premium audio', '7 seat option'],
      recommended: true,
      specs: createSpecs({
        engine: 'Dual Motor Electric',
        horsepower: '384 hp',
        torque: '376 lb-ft',
        transmission: 'Single-Speed',
        drivetrain: 'AWD',
        fuelEconomy: '123 MPGe',
        seating: '5-7',
        cargo: '68 cu ft',
        heatedSeats: true,
        navigationSystem: true,
        premiumAudio: true,
        adaptiveCruise: true,
        blindSpotMonitor: true,
        automaticEmergencyBraking: true,
        surroundViewCamera: true,
      }),
    },
    { 
      id: 'performance', 
      name: 'Performance', 
      price: '$53,990', 
      features: ['All Long Range features', '3.5s 0-60', 'Track Mode', 'Performance brakes', 'Lowered suspension'],
      specs: createSpecs({
        engine: 'Dual Motor Electric',
        horsepower: '510 hp',
        torque: '471 lb-ft',
        transmission: 'Single-Speed',
        drivetrain: 'AWD',
        fuelEconomy: '115 MPGe',
        seating: '5',
        cargo: '68 cu ft',
        heatedSeats: true,
        navigationSystem: true,
        premiumAudio: true,
        adaptiveCruise: true,
        blindSpotMonitor: true,
        automaticEmergencyBraking: true,
        surroundViewCamera: true,
      }),
    },
  ],

  // ============== BMW ==============
  'BMW 3 Series': [
    { 
      id: '330i', 
      name: '330i', 
      price: '$46,200', 
      features: ['8.8" display', 'Apple CarPlay', 'BMW Safety features', 'LED headlights', 'Sport seats'],
      specs: createSpecs({
        engine: '2.0L Turbo 4-Cylinder',
        horsepower: '255 hp',
        torque: '295 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'RWD',
        fuelEconomy: '26/36 mpg',
        cargo: '17.0 cu ft',
        leatherSeats: true,
        blindSpotMonitor: true,
      }),
    },
    { 
      id: '330i-xdrive', 
      name: '330i xDrive', 
      price: '$48,200', 
      features: ['All 330i features', 'xDrive AWD', 'Heated seats', 'Remote start', 'Park assist'],
      recommended: true,
      specs: createSpecs({
        engine: '2.0L Turbo 4-Cylinder',
        horsepower: '255 hp',
        torque: '295 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'AWD',
        fuelEconomy: '25/34 mpg',
        cargo: '17.0 cu ft',
        heatedSeats: true,
        leatherSeats: true,
        remoteStart: true,
        blindSpotMonitor: true,
        parkingAssist: true,
      }),
    },
    { 
      id: 'm340i', 
      name: 'M340i', 
      price: '$58,200', 
      features: ['382hp B58 I6', 'M Sport brakes', 'Adaptive suspension', 'M Sport styling', 'Track mode'],
      specs: createSpecs({
        engine: '3.0L Turbo 6-Cylinder',
        horsepower: '382 hp',
        torque: '369 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'RWD',
        fuelEconomy: '23/32 mpg',
        cargo: '17.0 cu ft',
        heatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        premiumAudio: true,
        remoteStart: true,
        blindSpotMonitor: true,
        adaptiveCruise: true,
        parkingAssist: true,
      }),
    },
    { 
      id: 'm340i-xdrive', 
      name: 'M340i xDrive', 
      price: '$60,200', 
      features: ['All M340i features', 'xDrive AWD', 'M Sport diff', 'Launch control', 'Enhanced exhaust'],
      specs: createSpecs({
        engine: '3.0L Turbo 6-Cylinder',
        horsepower: '382 hp',
        torque: '369 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'AWD',
        fuelEconomy: '23/31 mpg',
        cargo: '17.0 cu ft',
        heatedSeats: true,
        ventilatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        navigationSystem: true,
        premiumAudio: true,
        wirelessCharging: true,
        remoteStart: true,
        blindSpotMonitor: true,
        adaptiveCruise: true,
        parkingAssist: true,
        surroundViewCamera: true,
        headsUpDisplay: true,
      }),
    },
  ],

  // ============== MERCEDES-BENZ ==============
  'Mercedes-Benz C-Class': [
    { 
      id: 'c300', 
      name: 'C 300', 
      price: '$48,100', 
      features: ['11.9" touchscreen', 'Apple CarPlay', 'Active brake assist', 'LED headlights', 'MBUX infotainment'],
      specs: createSpecs({
        engine: '2.0L Turbo 4-Cylinder',
        horsepower: '255 hp',
        torque: '295 lb-ft',
        transmission: '9-Speed Auto',
        drivetrain: 'RWD',
        fuelEconomy: '25/35 mpg',
        cargo: '12.6 cu ft',
        leatherSeats: true,
        blindSpotMonitor: true,
      }),
    },
    { 
      id: 'c300-4matic', 
      name: 'C 300 4MATIC', 
      price: '$50,100', 
      features: ['All C 300 features', '4MATIC AWD', 'Heated seats', 'Ambient lighting', 'Burmester audio'],
      recommended: true,
      specs: createSpecs({
        engine: '2.0L Turbo 4-Cylinder',
        horsepower: '255 hp',
        torque: '295 lb-ft',
        transmission: '9-Speed Auto',
        drivetrain: 'AWD',
        fuelEconomy: '24/33 mpg',
        cargo: '12.6 cu ft',
        heatedSeats: true,
        leatherSeats: true,
        premiumAudio: true,
        blindSpotMonitor: true,
        wirelessCharging: true,
      }),
    },
    { 
      id: 'amg-c43', 
      name: 'AMG C 43', 
      price: '$60,600', 
      features: ['402hp Turbo I4', 'AMG suspension', 'AMG styling', 'Performance exhaust', 'AMG seats'],
      specs: createSpecs({
        engine: '2.0L Turbo 4-Cylinder + EQ Boost',
        horsepower: '402 hp',
        torque: '369 lb-ft',
        transmission: '9-Speed Auto',
        drivetrain: 'AWD',
        fuelEconomy: '23/30 mpg',
        cargo: '12.6 cu ft',
        heatedSeats: true,
        ventilatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        navigationSystem: true,
        premiumAudio: true,
        wirelessCharging: true,
        blindSpotMonitor: true,
        adaptiveCruise: true,
        parkingAssist: true,
        surroundViewCamera: true,
      }),
    },
  ],

  // ============== AUDI ==============
  'Audi A4': [
    { 
      id: '40-premium', 
      name: '40 Premium', 
      price: '$43,800', 
      features: ['10.1" touchscreen', 'Apple CarPlay', 'Audi pre sense', 'LED headlights', 'Virtual cockpit'],
      specs: createSpecs({
        engine: '2.0L Turbo 4-Cylinder',
        horsepower: '201 hp',
        torque: '236 lb-ft',
        transmission: '7-Speed DCT',
        drivetrain: 'FWD',
        fuelEconomy: '27/35 mpg',
        cargo: '12.0 cu ft',
        leatherSeats: true,
      }),
    },
    { 
      id: '40-premium-plus', 
      name: '40 Premium Plus', 
      price: '$48,300', 
      features: ['All Premium features', 'Bang & Olufsen audio', 'Navigation', 'Wireless charging', 'Park assist'],
      recommended: true,
      specs: createSpecs({
        engine: '2.0L Turbo 4-Cylinder',
        horsepower: '201 hp',
        torque: '236 lb-ft',
        transmission: '7-Speed DCT',
        drivetrain: 'AWD',
        fuelEconomy: '26/33 mpg',
        cargo: '12.0 cu ft',
        heatedSeats: true,
        leatherSeats: true,
        navigationSystem: true,
        premiumAudio: true,
        wirelessCharging: true,
        blindSpotMonitor: true,
        parkingAssist: true,
      }),
    },
    { 
      id: '45-prestige', 
      name: '45 Prestige', 
      price: '$54,000', 
      features: ['261hp Turbo', 'All Premium Plus features', 'Matrix LED', 'Head-up display', 'Adaptive suspension'],
      specs: createSpecs({
        engine: '2.0L Turbo 4-Cylinder',
        horsepower: '261 hp',
        torque: '273 lb-ft',
        transmission: '7-Speed DCT',
        drivetrain: 'AWD',
        fuelEconomy: '24/31 mpg',
        cargo: '12.0 cu ft',
        heatedSeats: true,
        ventilatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        navigationSystem: true,
        premiumAudio: true,
        wirelessCharging: true,
        blindSpotMonitor: true,
        adaptiveCruise: true,
        parkingAssist: true,
        surroundViewCamera: true,
        headsUpDisplay: true,
      }),
    },
    { 
      id: 's4', 
      name: 'S4 Premium Plus', 
      price: '$56,800', 
      features: ['349hp V6', 'Quattro AWD', 'Sport diff', 'Sport exhaust', 'S Sport seats'],
      specs: createSpecs({
        engine: '3.0L Turbo V6',
        horsepower: '349 hp',
        torque: '369 lb-ft',
        transmission: '8-Speed Auto',
        drivetrain: 'AWD',
        fuelEconomy: '21/30 mpg',
        cargo: '12.0 cu ft',
        heatedSeats: true,
        ventilatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        navigationSystem: true,
        premiumAudio: true,
        wirelessCharging: true,
        blindSpotMonitor: true,
        adaptiveCruise: true,
        parkingAssist: true,
        surroundViewCamera: true,
        headsUpDisplay: true,
      }),
    },
  ],
};

// Get trims for a specific vehicle
export const getVehicleTrims = (make: string, model: string, priceMin: number, priceMax: number): TrimData[] => {
  const key = `${make} ${model}`;
  
  // Return specific trims if we have them
  if (vehicleTrims[key]) {
    return vehicleTrims[key];
  }
  
  // Generate generic trims based on price range
  const midPrice = Math.round((priceMin + priceMax) / 2);
  const upperMidPrice = Math.round(priceMin + (priceMax - priceMin) * 0.7);
  
  return [
    {
      id: 'base',
      name: 'Base',
      price: `$${priceMin.toLocaleString()}`,
      features: ['Standard infotainment', 'Safety assist features', 'LED headlights', 'Rear camera', 'Bluetooth'],
      specs: createSpecs({
        engine: 'Standard Engine',
        fuelEconomy: 'See dealer',
      }),
    },
    {
      id: 'mid',
      name: 'Select',
      price: `$${midPrice.toLocaleString()}`,
      recommended: true,
      features: ['All Base features plus:', 'Larger touchscreen', 'Heated seats', 'Remote start', 'Premium audio'],
      specs: createSpecs({
        engine: 'Standard Engine',
        fuelEconomy: 'See dealer',
        heatedSeats: true,
        remoteStart: true,
        blindSpotMonitor: true,
      }),
    },
    {
      id: 'premium',
      name: 'Premium',
      price: `$${upperMidPrice.toLocaleString()}`,
      features: ['All Select features plus:', 'Leather seating', 'Sunroof', 'Advanced safety', 'Wireless charging'],
      specs: createSpecs({
        engine: 'Standard Engine',
        fuelEconomy: 'See dealer',
        heatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        wirelessCharging: true,
        remoteStart: true,
        blindSpotMonitor: true,
        adaptiveCruise: true,
      }),
    },
    {
      id: 'top',
      name: 'Limited',
      price: `$${priceMax.toLocaleString()}`,
      features: ['All Premium features plus:', 'Ventilated seats', 'Panoramic roof', 'Navigation', 'Surround view camera'],
      specs: createSpecs({
        engine: 'Upgraded Engine',
        fuelEconomy: 'See dealer',
        heatedSeats: true,
        ventilatedSeats: true,
        leatherSeats: true,
        sunroof: true,
        navigationSystem: true,
        premiumAudio: true,
        wirelessCharging: true,
        remoteStart: true,
        blindSpotMonitor: true,
        adaptiveCruise: true,
        parkingAssist: true,
        surroundViewCamera: true,
        headsUpDisplay: true,
      }),
    },
  ];
};

// Get recommended trim name for a vehicle
export const getRecommendedTrimName = (make: string, model: string): string => {
  const key = `${make} ${model}`;
  
  if (vehicleTrims[key]) {
    const recommended = vehicleTrims[key].find(trim => trim.recommended);
    return recommended?.name || vehicleTrims[key][1]?.name || 'Select';
  }
  
  return 'Select';
};

// Check if vehicle has specific trims in database
export const hasSpecificTrims = (make: string, model: string): boolean => {
  const key = `${make} ${model}`;
  return !!vehicleTrims[key];
};

// Get all available vehicles with trims
export const getAvailableVehicles = (): string[] => {
  return Object.keys(vehicleTrims);
};
